events {}
http {
  server {
    listen 80;
    server_name ~^(?<subdomain>.+)\.localhost$;

    location = / {
      resolver 127.0.0.11;
      set $backend "http://minio:9000/deployments/$subdomain/index.html";
      proxy_pass $backend;
      proxy_set_header Host minio:9000;
    }

    location / {
      resolver 127.0.0.11;
      set $backend "http://minio:9000/deployments/$subdomain$request_uri";
      proxy_pass $backend;
      proxy_set_header Host minio:9000;
    }
  }
}
